name: "Report a Security Vulnerability"
description: "Use this form to report any security vulnerabilities you have discovered."
title: "[Security]: "  # پیش‌فرض عنوان
labels: ["security"]   # برچسب امنیتی
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Security Disclosure Agreement
        
        Please do not disclose security vulnerabilities publicly until they are resolved. Describe the vulnerability below, and we will review it as soon as possible. Thank you for helping us keep this project safe!

  - type: input
    id: vulnerability_title
    attributes:
      label: Vulnerability Title
      description: "Provide a short, clear title describing the security vulnerability."
      placeholder: "e.g., SQL Injection in Login Form"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Describe the vulnerability in detail, including any potential impact."
      placeholder: "Explain the security issue here..."

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: "List the steps to reproduce the vulnerability. Be as detailed as possible so we can replicate the issue."
      placeholder: "1. Go to login page\n2. Enter a special payload\n3. Observe the unexpected behavior..."

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "Describe the expected secure behavior of the application if the vulnerability did not exist."
      placeholder: "Explain how the application should behave securely..."

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: "Explain what actually happens, highlighting the security issue."
      placeholder: "Describe the actual insecure behavior..."

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: "If you have any other context, screenshots, videos, or links (e.g., to CodeSandbox) that demonstrate the vulnerability, please add them here."
      placeholder: "Drag and drop screenshots or videos here, or include links..."

  - type: input
    id: contact_info
    attributes:
      label: Contact Information (Optional)
      description: "Provide your contact information if you'd like us to reach out for further clarification."
      placeholder: "Your email or GitHub handle (optional)"
